name: aisg-comp
channels: 
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pip=23.0.1
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - pyarrow=11.0.0
  - ipython=8.12.0
  - pip:
    - ipykernel==6.22.0